name: Integration Release Action
description: Releases a new version of an integration for a HashiCorp product
runs:
  main: 'notify-release.sh'
inputs:
  github_token:
    description: 'A GitHub Token to validate the release notification is coming from the registered repository'
    required: true
  integration_identifier:
    description: 'The identifier of the integration (e.g. "waypoint/nomad-plugin")'
    required: true
  release_version:
    description: 'The version of the release to make'
    required: true
  release_sha:
    description: 'The git SHA pointing to the commit of the release'
    required: true
